# Generated by Django 5.0.4 on 2024-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_produit_active_produit_category_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='sold',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(blank=True, choices=[('Dresses', 'Dresses'), ('Pants', 'Pants'), ('T-shirts', 'T-shirts'), ('Shoes', 'Shoes'), ('Jackets', 'Jackets')], max_length=50, null=True),
        ),
    ]
