# Generated by Django 5.0.4 on 2024-05-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_produit_sold_alter_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
