# Generated by Django 5.0.4 on 2024-05-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_produit_oldprix_remove_produit_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='nom',
        ),
    ]
