# Generated by Django 5.0.4 on 2024-05-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_name_client_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ville',
            new_name='phone',
        ),
    ]
