# Generated by Django 5.0.4 on 2024-05-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_ville_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(default='photos/24/04/30/new.jpg', upload_to='photos/%y/%m/%d')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
