# Generated by Django 5.0.4 on 2024-05-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='category',
            field=models.CharField(choices=[('Dresses', 'Dresses'), ('Pants', 'Pants'), ('T-shirts', 'T-shirts'), ('Shoes', 'Shoes'), ('Jackets', 'Jackets')], max_length=50),
        ),
    ]
