# Generated by Django 5.0.4 on 2024-05-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_cart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='category',
            field=models.CharField(choices=[('Dresses', 'Dresses'), ('Pants', 'Pants'), ('T-shirts', 'T-shirts'), ('Shoes', 'Shoes'), ('Jackets', 'Jackets')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='content',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
