# Generated by Django 5.0.4 on 2024-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_cart_category_alter_cart_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(default='photos/24/04/30/new.jpg', null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
