# Generated by Django 5.0.4 on 2024-05-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_cart_image_alter_cart_label_alter_cart_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
    ]
