# Generated by Django 5.0.4 on 2024-05-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='content',
        ),
    ]
